language: ruby
rvm:
- 2.6.5
services:
- postgresql
script:
- bundle exec rake db:create RAILS_ENV=test
- bundle exec rake db:migrate RAILS_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: FGItEH969EnVB1qSie/RqtkL7+CeVV7xShn380y+wGSgaTSo+OFQDg4HJ8haN9Nol6lp9VDkJtCSa4wsJXOyA0+6fUWWbr/7FSHaZCXNq5xjGgkfo+kXt0IYiNAqErmZZ3gDJg3kjpoaO7YtHwBFZ9vHWfk75Lbr8k6TtF+KDqx9xhoaD4mcUaInwZOW8oiYv0YDOpJ3MJwUxDnRne3lGvqRMITdMaOoWaQEeh/lU0icotbeMemCN3FQX+shjSBm2s1AY0qgt1ZocU/bXSZn6A+RPzY0hxEyrcZKhdKf0O5Wzo/mBmfWUqPtNCmers7+BsPc3LQHOhzgFGbTawnZQ3XI/r6jaNSv2tBxxgQgftYOHHEGVBpYLOvagil2l6cG2SBJXXutdXO1QLzdduliDgzHsfm3WE224EMIrQb+moLnPnuQRTapvg2LtzctBlD/xdyS2Amkl5ACXKvzCBgRdUvwhfmr0eb8uRJpDG3Q2SkXlujUQSr9h5NeOO6k/NepRbEmYsCZVLHnTfQPQGkh/37l/tpDtDcMX5WZVeO2GwGxiWIilxsDrruPh6vXx3QV8Q0Ja7aYLzOofs8/pK0PwKBJyBrHddbxp6rNq5EjqYGfDdvSIHItdeEM42hOBc4kIKnqsytw0uGNjDPSmHw8wjooZQezp1Tu10rt0lrET6Y=
  app: api-marketplace-discos
  on:
    repo: Israel-Ferreira/api-marketplace-discos
  run:
  - rails db:migrate
